name: ci-unit-test

on:
  push:
    branches:
      - "*"
      - "!main"

jobs:
  unit-test:
    # skip the test of release bot opened PR to main
    if: ${{ !contains(github.ref, 'release') }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      # - name: Run tests
      #  run: npm run test
