name: cd-staging-deploy

on:
  push:
    branches:
      - "staging"

jobs:
  deploy-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: deploy-to-vercel-staging
        id: deployToVercelStaging
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required
          scope: ${{ secrets.VERCEL_ORG_ID }}
          github-comment: false
          # working-directory: ./sub-directory

      - name: Comment
        uses: NejcZdovc/comment-pr@v1.1.1
        with:
          file: "templates/vercel-deploy-comment.md"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          BRANCH: "staging"
          PREVIEW_URL: ${{steps.deployToVercelStaging.outputs.preview-url}}
