name: cd-staging-deploy

on:
  push:
    branches:
      - 'staging'

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: deploy-to-vercel-staging
        id: deployToVercelStaging
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required 
          scope: ${{ secrets.VERCEL_ORG_ID }}
          github-comment: false
          # working-directory: ./sub-directory
      
      - name: Render template
        id: template
        uses: chuhlomin/render-template@v1.2
        with:
          template: .github/templates/vercel-deploy-comment.md
          vars: |
            branch: staging
            preview-url: ${{ $steps.deployToVercelStaging.outputs.preview-url }}

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ${{ steps.template.outputs.result }}
          reactions: rocket

    