name: ci-webpack-stats-diff

on:
  pull_request:
    branches:
      - 'staging'

jobs:
  build-head:
    name: 'Build head'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload stats
        uses: actions/upload-artifact@v2
        with:
          name: head-stats
          path: .next/analyze/client.json

  build-base:
    name: 'Build base'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ## github.base.ref only work at pull_request, it means the branch we want to pull into
          ref: ${{ github.base_ref }}

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload stat
        uses: actions/upload-artifact@v2
        with:
          name: base-stats
          path: .next/analyze/client.json

  compare-diff:
    name: 'Compare bundle sizes difference'
    runs-on: ubuntu-latest
    needs: [build-head, build-base]
    steps: 
      - name: Download base artifact
        uses: actions/download-artifact@v2
        with:
          name: base-stats

      - name: Download head artifact
        uses: actions/download-artifact@v2
        with:
          name: head-stats

      - name: Diff between base & head
        uses: chronotruck/webpack-stats-diff-action@1.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment_title: 'Bundle difference'
          base_stats_path: ./base-stats/client.json
          head_stats_path: ./head-stats/client.json

